import Head from "next/head";

import { api } from "~/utils/api";
import { Todos } from "./components/Todos";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

export default function Home() {
  const todos = api.todos.getTodos.useQuery();
  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
      {
          user.isSignedIn ? 
          <>
            <h1 className="text-white">Welcom to T3 Stack Project</h1>            
            <Todos todos = {todos.data}/>
            <button className="bg-white"><SignOutButton/></button>
          </> 
          : 
          <>
            <h1 className="text-white">Hello</h1>          
            <button className="bg-white"><SignInButton /></button>
          </>
        }     
      </main>
    </>
  );
}